import { Keyboard } from "@raycast/api";

export const SHORTCUTS = {
  browseInConfig: { key: "o", modifiers: ["cmd"] } as Keyboard.Shortcut,
  copy: Keyboard.Shortcut.Common.Copy,
  copyDeeplink: { key: "c", modifiers: ["cmd", "shift"] } as Keyboard.Shortcut,
  copyPathDeeplink: { key: "p", modifiers: ["cmd", "shift"] } as Keyboard.Shortcut,
  createOverride: { key: "e", modifiers: ["cmd", "shift"] } as Keyboard.Shortcut,
  createQuicklink: { key: "l", modifiers: ["cmd"] } as Keyboard.Shortcut,
  createPathQuicklink: { key: "l", modifiers: ["cmd", "shift"] } as Keyboard.Shortcut,
  delete: Keyboard.Shortcut.Common.Remove,
  edit: Keyboard.Shortcut.Common.Edit,
  editFallbackPaths: { key: "f", modifiers: ["cmd", "shift"] } as Keyboard.Shortcut,
  editMacroSteps: { key: "m", modifiers: ["cmd"] } as Keyboard.Shortcut,
  editTapAction: { key: "t", modifiers: ["cmd"] } as Keyboard.Shortcut,
  moveDown: Keyboard.Shortcut.Common.MoveDown,
  moveUp: Keyboard.Shortcut.Common.MoveUp,
  newAction: Keyboard.Shortcut.Common.New,
  newGroup: { key: "n", modifiers: ["cmd", "shift"] } as Keyboard.Shortcut,
  newLayer: { key: "n", modifiers: ["cmd", "opt"] } as Keyboard.Shortcut,
  openCommandScout: Keyboard.Shortcut.Common.Open,
  openInEditor: { key: "return", modifiers: ["cmd"] } as Keyboard.Shortcut,
  openPathEditor: { key: "p", modifiers: ["cmd", "ctrl"] } as Keyboard.Shortcut,
  primary: Keyboard.Shortcut.Common.Open,
  refresh: Keyboard.Shortcut.Common.Refresh,
  removeTapAction: { key: "backspace", modifiers: ["cmd", "shift"] } as Keyboard.Shortcut,
  save: Keyboard.Shortcut.Common.Save,
  searchValueSource: { key: "f", modifiers: ["cmd"] } as Keyboard.Shortcut,
  showDetails: { key: ".", modifiers: ["cmd"] } as Keyboard.Shortcut,
  siblingAction: Keyboard.Shortcut.Common.New,
  siblingGroup: { key: "n", modifiers: ["cmd", "shift"] } as Keyboard.Shortcut,
  siblingLayer: { key: "n", modifiers: ["cmd", "opt"] } as Keyboard.Shortcut,
  toggleEnabled: { key: "t", modifiers: ["cmd"] } as Keyboard.Shortcut,
  childAction: { key: "n", modifiers: ["cmd", "ctrl"] } as Keyboard.Shortcut,
  childGroup: { key: "n", modifiers: ["cmd", "ctrl", "shift"] } as Keyboard.Shortcut,
  childLayer: { key: "n", modifiers: ["cmd", "ctrl", "opt"] } as Keyboard.Shortcut,
  paste: { key: "v", modifiers: ["cmd"] } as Keyboard.Shortcut,
} as const;
