// Generated by Leader Key. Do not edit this file directly.
import type { ComplexModifications } from '../../src/karabiner/karabiner-config.ts'
import rawDefaultComplexModifications from './default-complex-modifications.json'

export const defaultProfileName = "Default"
export const defaultComplexModificationsSha256 = "52b50820e89be06cf55a0808b01611d33aa00643fb6a097239a90a702e2c2d4e"

export type KarabinerConfigLike = {
  profiles: Array<{
    name: string
    [key: string]: unknown
  }>
  [key: string]: unknown
}

export const defaultComplexModifications = rawDefaultComplexModifications as ComplexModifications

export function replaceProfileComplexModifications<T extends KarabinerConfigLike>(
  config: T,
  profileName = defaultProfileName,
): T {
  let found = false

  const profiles = config.profiles.map((profile) => {
    if (profile.name !== profileName) {
      return profile
    }

    found = true
    return {
      ...profile,
      complex_modifications: defaultComplexModifications,
    }
  })

  if (!found) {
    throw new Error(`Profile ${profileName} not found`)
  }

  return {
    ...config,
    profiles,
  } as T
}