// Generated by Leader Key. Do not edit this file directly.
import type { ComplexModifications } from '../../src/karabiner/karabiner-config.ts'
import rawDefaultComplexModifications from './default-complex-modifications.json'

export const defaultProfileName = "Default"
export const defaultComplexModificationsSha256 = "90bb48ea0526cc6172a8fc1f3f1b56b7b521cb2a465f0d6511ef9fa3eb0be542"

export type KarabinerConfigLike = {
  profiles: Array<{
    name: string
    [key: string]: unknown
  }>
  [key: string]: unknown
}

export const defaultComplexModifications = rawDefaultComplexModifications as ComplexModifications

export function replaceProfileComplexModifications<T extends KarabinerConfigLike>(
  config: T,
  profileName = defaultProfileName,
): T {
  let found = false

  const profiles = config.profiles.map((profile) => {
    if (profile.name !== profileName) {
      return profile
    }

    found = true
    return {
      ...profile,
      complex_modifications: defaultComplexModifications,
    }
  })

  if (!found) {
    throw new Error(`Profile ${profileName} not found`)
  }

  return {
    ...config,
    profiles,
  } as T
}