import Carbon.HIToolbox
// swiftlint:disable type_body_length
import Cocoa
import Combine
import Defaults
import Kingfisher
import SwiftUI

// Define a unique tag for synthetic events generated by Leader Key
private let leaderKeySyntheticEventTag: Int64 = 0xDEAD_BEEF  // Use a unique value

enum KeyHelpers: UInt16 {
  case enter = 36
  case tab = 48
  case space = 49
  case backspace = 51
  case escape = 53
  case upArrow = 126
  case downArrow = 125
  case leftArrow = 123
  case rightArrow = 124
}

class Controller {
  var userState: UserState
  var userConfig: UserConfig
  weak var appDelegate: AppDelegate?  // Add weak reference to AppDelegate
  var keyLookupCache: KeyLookupCache?  // O(1) key lookup, set by AppDelegate on sequence start

  var window: MainWindow!
  private var cheatsheetWindow: NSWindow?
  private var cheatsheetTimer: Timer?

  private var cancellables = Set<AnyCancellable>()

  // Track currently held modifier keys for keydown/keyup control
  private var heldModifierKeys = Set<CGKeyCode>()

  init(userState: UserState, userConfig: UserConfig, appDelegate: AppDelegate) {
    self.userState = userState
    self.userConfig = userConfig
    self.appDelegate = appDelegate  // Store the reference

    Task {
      for await value in Defaults.updates(.theme) {
        let windowClass = Theme.classFor(value)
        self.window = await windowClass.init(controller: self)
      }
    }

    Events.sink { event in
      switch event {
      case .didReload:
        ViewSizeCache.shared.clear()  // invalidate cached sizes when config changes
      default: break
      }
    }.store(in: &cancellables)

    // Lazily create cheatsheet to reduce baseline memory
    self.cheatsheetWindow = nil
  }

  func show() {
    show(completion: nil)
  }

  // Define an enum for activation type
  enum ActivationType {
    case defaultOnly
    case appSpecificWithFallback
    case fallbackOnly
  }

  func show(type: ActivationType = .appSpecificWithFallback, bundleId: String? = nil, completion: (() -> Void)? = nil) {
    // IMPORTANT: Detect overlay state BEFORE sending activation events
    // This prevents overlay apps from hiding their overlays before we can detect them
    let configToLoad: Group
    let configKeyForSettings: String  // Track which config key to show in settings

    switch type {
    case .defaultOnly:
      configToLoad = userConfig.root  // Use the already loaded default config
      configKeyForSettings = globalDefaultDisplayName
    case .appSpecificWithFallback:
      // Check if we have a specific bundleId override (like "__FALLBACK__")
      if let overrideBundleId = bundleId, overrideBundleId == "__FALLBACK__" {
        // For __FALLBACK__, use the fallback config with all items marked as fallback
        configToLoad = userConfig.getMarkedFallbackConfig()  // This marks all items with isFromFallback
        configKeyForSettings = defaultAppConfigDisplayName  // Show as "Fallback App Config"
      } else {
        // Use bundleId from Karabiner (single source of truth for app detection)
        configToLoad = userConfig.getConfig(for: bundleId)

        // Determine the config key to use in settings
        if let bundleId = bundleId {
          // Look for the display name that matches this bundle ID in discovered configs
          var foundConfigKey: String? = nil
          for (displayKey, _) in userConfig.discoveredConfigFiles {
            if displayKey != globalDefaultDisplayName && displayKey != defaultAppConfigDisplayName {
              // Check if this key is for the current bundle ID
              if let extractedId = userConfig.extractBundleId(from: displayKey),
                extractedId == bundleId
              {
                foundConfigKey = displayKey
                break
              }
            }
          }
          configKeyForSettings = foundConfigKey ?? defaultAppConfigDisplayName
        } else {
          // No bundle ID, use the default
          configKeyForSettings = globalDefaultDisplayName
        }
      }
    case .fallbackOnly:
      configToLoad = userConfig.getFallbackConfig()  // Load only the fallback config
      configKeyForSettings = defaultAppConfigDisplayName  // Use fallback display name
    }

    // Now send activation events after detection is complete
    Events.send(.willActivate)

    userState.activeRoot = configToLoad  // Update UserState with the selected config
    userState.activeConfigKey = configKeyForSettings  // Store the config key for settings
    userState.activeBundleId = bundleId == "__FALLBACK__" ? nil : bundleId
    userState.isActive = true  // Mark Leader Key as active

    // --- Start Screen Positioning Logic (Moved back before show) ---
    var calculatedOrigin: NSPoint?  // Store calculated origin

    // Get the current mouse location
    let mouseLocation = NSEvent.mouseLocation
    let screen = screenContainingMouse(mouseLocation)

    if let targetScreen = screen {
      let screenFrame = targetScreen.visibleFrame  // Use visibleFrame to account for menu bar and Dock
      let windowSize = self.window.frame.size

      // Check if window size is valid before calculating position
      if windowSize.width > 0 && windowSize.height > 0 {
        // Calculate the desired origin: Center horizontally, but vertically place so that
        // the TOP of the window is `panelTopOffsetPercent` of the visible frame height
        let verticalPercent = CGFloat(Defaults[.panelTopOffsetPercent])
        let newOriginX = screenFrame.origin.x + (screenFrame.size.width - windowSize.width) / 2.0
        let newOriginY =
          (screenFrame.origin.y + screenFrame.size.height)
          - (screenFrame.size.height * verticalPercent) - windowSize.height
        calculatedOrigin = NSPoint(x: newOriginX, y: newOriginY)

        debugLog("[Controller show] Calculated Origin: \(calculatedOrigin!)")

      } else {
        // Fallback: Window size is zero.
        debugLog(
          "[Controller show] Warning: Window size \(windowSize) is invalid. Will center window.")
        // calculatedOrigin remains nil, will be handled below
      }
    } else {
      // Fallback: Should not happen
      debugLog("[Controller show] Warning: Could not determine target screen. Will center window.")
      // calculatedOrigin remains nil, will be handled below
    }
    // --- End Screen Positioning Logic ---

    // Show the window, passing the calculated origin (or nil for centering)
    window.show(at: calculatedOrigin) {  // Pass origin to the modified show function
      // Completion handler remains empty for positioning logic
      Events.send(.didActivate)
      completion?()
    }

    // Apply click-through preference and reset transparency.
    ThreadOptimization.executeOnMain {
      self.window.alphaValue = Defaults[.normalModeOpacity]
      self.window.ignoresMouseEvents = Defaults[.panelClickThrough]
    }

    if !window.hasCheatsheet {
      return
    }

    switch Defaults[.autoOpenCheatsheet] {
    case .always:
      showCheatsheet()
    case .delay:
      scheduleCheatsheet()
    default: break
    }
  }

  func hide(afterClose: (() -> Void)? = nil) {
    Events.send(.willDeactivate)

    // Mark Leader Key as inactive immediately
    userState.isActive = false

    // Release any held modifier keys before hiding
    releaseAllHeldModifiers()

    window.hide {
      afterClose?()
      self.clear()  // Clear UserState *after* external completion (e.g., AppDelegate reset) to avoid premature UI changes

      Events.send(.didDeactivate)
    }

    // Fully close cheatsheet so AppKit releases it (we recreate lazily)
    cheatsheetWindow?.close()
    // Release cheatsheet window to free memory when not visible
    cheatsheetWindow = nil
    cheatsheetTimer?.invalidate()

    // Proactively drop in-memory image caches when panel is hidden
    KingfisherManager.shared.cache.clearMemoryCache()
  }

  func keyDown(with event: NSEvent) {
    // Reset the delay timer
    if Defaults[.autoOpenCheatsheet] == .delay {
      scheduleCheatsheet()
    }

    // Handle Command key shortcuts when the window is key
    if event.modifierFlags.contains(.command) {
      switch event.charactersIgnoringModifiers {
      case ",":
        debugLog("[Controller] Cmd+, detected. Opening settings.")
        NSApp.sendAction(
          #selector(AppDelegate.settingsMenuItemActionHandler(_:)), to: nil,
          from: nil)
        hide()  // Hide the main window when settings open
        return  // Consume the event
      case "w":
        debugLog("[Controller] Cmd+w detected. Hiding window.")
        hide()
        return  // Consume the event
      case "q":
        debugLog("[Controller] Cmd+q detected. Terminating app.")
        NSApp.terminate(nil)
        return  // Consume the event
      default:
        debugLog("[Controller] Unhandled Cmd+Key: \(event.charactersIgnoringModifiers ?? "nil")")
      // Let other Cmd key combinations pass through if needed
      }
    }

    // Handle non-Command key presses for sequence/navigation
    switch event.keyCode {
    case KeyHelpers.backspace.rawValue:
      clear()
      delay(1) {
        self.positionCheatsheetWindow()
      }
    case KeyHelpers.escape.rawValue:
      hide()
      return
    default:
      guard let char = charForEvent(event) else { return }
      handleKey(char, withModifiers: event.modifierFlags)
    }
  }

  func handleKey(_ key: String, withModifiers modifiers: NSEvent.ModifierFlags? = nil) {
    if key == "?" {
      showCheatsheet()
      return
    }

    // Use the activeRoot from UserState, fallback to default userConfig.root if needed
    let activeList = userState.activeRoot ?? userConfig.root
    let list =
      (userState.currentGroup != nil)
      ? userState.currentGroup : activeList  // Start search from active root

    // O(1) lookup via KeyLookupCache if available, fallback to linear scan
    let hit: ActionOrGroup?
    if let groupId = list?.id, let cached = keyLookupCache?.getItem(forKey: key, inGroupId: groupId) {
      hit = cached
    } else {
      hit = list?.actions.first { item in
        switch item {
        case .group(let group):
          if group.key == key {
            return true
          }
        case .action(let action):
          if action.key == key {
            return true
          }
        }
        return false
      }
    }

    switch hit {
    case .action(let action):
      if let mods = modifiers, isInStickyMode(mods) {
        runAction(action)
      } else {
        hide {
          self.runAction(action)
        }
      }
    case .group(let group):
      if let mods = modifiers, shouldRunGroupSequenceWithModifiers(mods) {
        hide {
          self.runGroup(group)
        }
      } else {
        // Check if the group has sticky mode enabled
        if group.stickyMode == true {
          if let appDelegate = appDelegate {
            appDelegate.activateStickyMode()
            debugLog(
              "[Controller] handleKey: Group has stickyMode enabled. Activating sticky mode.")
          } else {
            debugLog("[Controller] handleKey: Cannot activate sticky mode - appDelegate is nil")
          }
        }

        userState.display = group.key
        userState.navigateToGroup(group)
      }
    case .none:
      window.notFound()
    }

    // Why do we need to wait here?
    delay(1) {
      self.positionCheatsheetWindow()
    }
  }

  private func shouldRunGroupSequence(_ event: NSEvent) -> Bool {
    return shouldRunGroupSequenceWithModifiers(event.modifierFlags)
  }

  private func shouldRunGroupSequenceWithModifiers(_ modifierFlags: NSEvent.ModifierFlags) -> Bool {
    let config = Defaults[.modifierKeyConfiguration]

    switch config {
    case .controlGroupOptionSticky:
      return modifierFlags.contains(.control)
    case .optionGroupControlSticky:
      return modifierFlags.contains(.option)
    }
  }

  private func isInStickyMode(_ modifierFlags: NSEvent.ModifierFlags) -> Bool {
    let config = Defaults[.modifierKeyConfiguration]

    switch config {
    case .controlGroupOptionSticky:
      return modifierFlags.contains(.option)
    case .optionGroupControlSticky:
      return modifierFlags.contains(.control)
    }
  }

  private func charForEvent(_ event: NSEvent) -> String? {
    if Defaults[.forceEnglishKeyboardLayout] {
      if let mapped = englishKeymap[event.keyCode] {
        // Check if Shift is pressed and convert to uppercase if so
        if event.modifierFlags.contains(.shift) {
          return mapped.uppercased()
        }

        return mapped
      }
    }

    // Handle special keys
    switch event.keyCode {
    case KeyHelpers.enter.rawValue:
      return "↵"
    case KeyHelpers.upArrow.rawValue:
      return "↑"
    case KeyHelpers.downArrow.rawValue:
      return "↓"
    case KeyHelpers.leftArrow.rawValue:
      return "←"
    case KeyHelpers.rightArrow.rawValue:
      return "→"
    default:
      return event.charactersIgnoringModifiers
    }
  }

  private func positionCheatsheetWindow() {
    guard let mainWindow = window, let cheatsheet = cheatsheetWindow else {
      return
    }

    cheatsheet.setFrameOrigin(
      mainWindow.cheatsheetOrigin(cheatsheetSize: cheatsheet.frame.size))
  }

  private func showCheatsheet() {
    if !window.hasCheatsheet { return }
    if cheatsheetWindow == nil {
      cheatsheetWindow = Cheatsheet.createWindow(for: userState)
    }
    positionCheatsheetWindow()
    cheatsheetWindow?.orderFront(nil)
  }

  private func scheduleCheatsheet() {
    cheatsheetTimer?.invalidate()

    cheatsheetTimer = Timer.scheduledTimer(
      withTimeInterval: Double(Defaults[.cheatsheetDelayMS]) / 1000.0, repeats: false
    ) { [weak self] _ in
      self?.showCheatsheet()
    }
  }

  func runGroup(_ group: Group) {
    for groupOrAction in group.actions {
      switch groupOrAction {
      case .group(let group):
        runGroup(group)
      case .action(let action):
        runAction(action)
      }
    }
  }

  func runAction(_ action: Action) {
    switch action.type {
    case .application:
      KarabinerUserCommandReceiver.openAppDirectly(action.value)
    case .url:
      openURL(action)
    case .command:
      CommandRunner.run(action.value)
    case .folder:
      let path: String = (action.value as NSString).expandingTildeInPath
      NSWorkspace.shared.selectFile(nil, inFileViewerRootedAtPath: path)
    case .shortcut:
      let success = runKeyboardShortcut(action.value)
      if !success {
        // If shortcut failed, we already showed an alert and reset state.
        // We might still need to hide if not in sticky mode, but the state is handled.
        debugLog(
          "[Controller] runAction: Detected shortcut failure. State should be reset by runKeyboardShortcut."
        )
      }
      // Always release held modifiers after shortcut execution for safety
      releaseAllHeldModifiers()
    case .text:
      typeText(action.value)
    case .toggleStickyMode:
      if let appDelegate = appDelegate {
        appDelegate.toggleStickyMode()
      } else {
        debugLog("[Controller] runAction: Cannot toggle sticky mode - appDelegate is nil")
      }
    case .macro:
      runMacro(action)
    case .menu:
      // Value format: "App > Menu > Item"
      let parts = action.value.components(separatedBy: " > ")
      guard parts.count >= 2 else {
        debugLog("[Controller] runAction: invalid menu value '\(action.value)' — expected 'App > Menu > Item'")
        break
      }
      let appName = parts[0].trimmingCharacters(in: .whitespaces)
      let menuPath = parts.dropFirst().map { $0.trimmingCharacters(in: .whitespaces) }.joined(separator: " > ")
      // Send as v1 payload to the receiver for AX-based menu clicking
      KarabinerUserCommandReceiver.selectMenuItemDirectly(
        app: appName,
        path: menuPath,
        fallbackPaths: action.menuFallbackPaths ?? []
      )
    case .intellij:
      // Value is action ID(s) e.g. "ReformatCode" or "SaveAll,ReformatCode"
      KarabinerUserCommandReceiver.sendToIntelliJSocket(action: action.value)
    case .keystroke:
      let keystrokeValue = KeystrokeActionValue.parse(action.value)
      KarabinerUserCommandReceiver.sendKeystroke(
        app: keystrokeValue.app,
        spec: keystrokeValue.spec,
        focusApp: keystrokeValue.focusTargetApp
      )
    default:
      debugLog("\(action.type) unknown")
    }

    // Check if this action has sticky mode enabled (except for Toggle Sticky Mode action)
    if action.type != .toggleStickyMode && action.stickyMode == true {
      if let appDelegate = appDelegate {
        appDelegate.activateStickyMode()
        debugLog("[Controller] runAction: Activated sticky mode for action with stickyMode enabled")
      } else {
        debugLog("[Controller] runAction: Cannot activate sticky mode - appDelegate is nil")
      }
    }

    if window.isVisible {
      window.orderFront(nil)
    }
  }

  func runMacro(_ action: Action) {
    guard let macroSteps = action.macroSteps else {
      debugLog("[Controller] runMacro: No macro steps found for action")
      return
    }

    debugLog("[Controller] runMacro: Starting macro with \(macroSteps.count) steps")

    // Execute macro steps asynchronously with delays
    DispatchQueue.global(qos: .userInitiated).async {
      for (index, step) in macroSteps.enumerated() {
        guard step.enabled else {
          debugLog("[Controller] runMacro: Step \(index + 1) is disabled, skipping")
          continue
        }

        // Apply delay before executing the step
        if step.delay > 0 {
          debugLog("[Controller] runMacro: Waiting \(step.delay) seconds before step \(index + 1)")
          Thread.sleep(forTimeInterval: step.delay)
        }

        debugLog("[Controller] runMacro: Executing step \(index + 1)/\(macroSteps.count)")

        // Execute the step action on the main thread
        ThreadOptimization.executeOnMain {
          self.runAction(step.action)
        }
      }

      debugLog("[Controller] runMacro: Completed macro execution")
    }
  }

  private func clear() {
    userState.clear()  // This now also resets activeRoot in UserState
  }

  // --- Repositioning Function --- START ---
  func repositionWindowNearMouse() {
    guard let window = self.window else {
      debugLog("[Controller reposition] Error: Window is nil. Cannot reposition.")
      return
    }

    var calculatedOrigin: NSPoint?
    let mouseLocation = NSEvent.mouseLocation
    let screen = screenContainingMouse(mouseLocation)

    if let targetScreen = screen {
      let screenFrame = targetScreen.visibleFrame
      let windowSize = window.frame.size  // Use the window instance directly

      if windowSize.width > 0 && windowSize.height > 0 {
        // Calculate the desired origin: Center horizontally, but vertically place so that
        // the TOP of the window is `panelTopOffsetPercent` of the visible frame height
        let verticalPercent = CGFloat(Defaults[.panelTopOffsetPercent])
        let newOriginX = screenFrame.origin.x + (screenFrame.size.width - windowSize.width) / 2.0
        let newOriginY =
          (screenFrame.origin.y + screenFrame.size.height)
          - (screenFrame.size.height * verticalPercent) - windowSize.height
        calculatedOrigin = NSPoint(x: newOriginX, y: newOriginY)
        debugLog("[Controller reposition] Calculated Origin: \(calculatedOrigin!)")
      } else {
        debugLog(
          "[Controller reposition] Warning: Window size \(windowSize) is invalid. Skipping reposition calculation."
        )
      }
    } else {
      debugLog(
        "[Controller reposition] Warning: Could not determine target screen. Skipping reposition calculation."
      )
    }

    // Apply the position if calculated, otherwise center
    if let originToSet = calculatedOrigin {
      window.setFrameOrigin(originToSet)
    } else {
      window.center()
    }
  }
  // --- Repositioning Function --- END ---

  private func openURL(_ action: Action) {
    let expandedURLValue: String
    switch URLPlaceholderExpander.expand(action.value, preferredFrontmostBundleId: userState.activeBundleId) {
    case .success(let value):
      expandedURLValue = value
    case .failure(let error):
      showAlert(title: "URL Placeholder Error", message: error.localizedDescription)
      return
    }

    guard let url = URL(string: expandedURLValue) else {
      showAlert(
        title: "Invalid URL", message: "Failed to parse URL: \(expandedURLValue)")
      return
    }

    guard let scheme = url.scheme else {
      showAlert(
        title: "Invalid URL",
        message:
          "URL is missing protocol (e.g. https://, raycast://): \(expandedURLValue)"
      )
      return
    }

    // Determine the configuration based on action.activates or scheme
    let configurationToUse: NSWorkspace.OpenConfiguration
    let shouldActivate: Bool

    if let explicitlySetActivates = action.activates {
      // User explicitly set the value
      shouldActivate = explicitlySetActivates
      debugLog(
        "[Controller] openURL: 'activates' explicitly set to \(shouldActivate) for \(expandedURLValue)")
    } else {
      // Fallback to default behavior based on scheme if activates is nil
      shouldActivate = (scheme == "http" || scheme == "https")
      debugLog(
        "[Controller] openURL: 'activates' not set, defaulting based on scheme ('\(scheme)') to \(shouldActivate) for \(expandedURLValue)"
      )
    }

    if shouldActivate {
      configurationToUse = NSWorkspace.OpenConfiguration()  // Default config activates
    } else {
      configurationToUse = DontActivateConfiguration.shared.configuration  // Shared config does not activate
    }

    // Open the URL with the determined configuration
    NSWorkspace.shared.open(
      url,
      configuration: configurationToUse
    )
  }

  private func showAlert(title: String, message: String) {
    // Run the alert on the main thread
    ThreadOptimization.executeOnMain {
      debugLog("[Controller showAlert] Displaying alert: Title='\(title)', Message='\(message)'")
      let alert = NSAlert()
      alert.messageText = title
      alert.informativeText = message
      alert.alertStyle = .warning
      alert.addButton(withTitle: "OK")
      // runModal will still block this async block, but not the original event handler
      let response = alert.runModal()
      debugLog(
        "[Controller showAlert async] Alert dismissed with response: \(response == .alertFirstButtonReturn ? "OK" : "Other")"
      )
    }
  }

  // --- Text Typing Helper --- START ---
  private func typeText(_ textToType: String) {
    debugLog("[Controller] Attempting to type text: '\(textToType)'")
    guard let source = CGEventSource(stateID: .hidSystemState) else {
      debugLog("Error: Failed to create CGEventSource for typing.")
      showAlert(title: "Typing Error", message: "Could not create event source.")
      return
    }
    let tapLocation = CGEventTapLocation.cghidEventTap

    // Loop through each character in the string
    for character in textToType {
      // Get the Unicode value(s) for the character
      guard let utf16Values = character.unicodeScalars.first?.value else {
        debugLog("Warning: Could not get Unicode value for character '\(character)'. Skipping.")
        continue
      }

      // Create KeyDown event
      guard let eventDown = CGEvent(keyboardEventSource: source, virtualKey: 0, keyDown: true)
      else {  // virtualKey 0 for Unicode
        debugLog("Error: Failed to create KeyDown CGEvent for character '\(character)'.")
        continue
      }
      var charCode = UniChar(utf16Values)
      eventDown.keyboardSetUnicodeString(stringLength: 1, unicodeString: &charCode)
      eventDown.post(tap: tapLocation)

      // Tiny delay (adjust as needed)
      // usleep(5000) // 5 milliseconds

      // Create KeyUp event
      guard let eventUp = CGEvent(keyboardEventSource: source, virtualKey: 0, keyDown: false)
      else {  // virtualKey 0 for Unicode
        debugLog("Error: Failed to create KeyUp CGEvent for character '\(character)'.")
        continue
      }
      eventUp.keyboardSetUnicodeString(stringLength: 1, unicodeString: &charCode)
      eventUp.post(tap: tapLocation)

      // Add a small delay between characters (optional, makes typing feel more natural)
      // usleep(10000) // 10 milliseconds
    }
    debugLog("[Controller] Finished typing text.")
  }
  // --- Text Typing Helper --- END ---

  // --- Shortcut Execution Helpers --- START ---
  //
  // Supported shortcut formats:
  // - Single shortcuts: "Ctab" (Cmd+Tab), "CSa" (Cmd+Shift+A)
  // - Sequences: "Ctab Oa" (Cmd+Tab then Option+A)
  // - Special commands:
  //   • "vk_none" - Release all modifier keys (Karabiner compatible)
  //   • "release_modifiers" - Release all modifier keys
  // - Example with release: "Ctab vk_none" (Cmd+Tab then release modifiers)

  private func runKeyboardShortcut(_ shortcutSequenceString: String) -> Bool {
    debugLog("[Controller] Attempting to run shortcut sequence: '\(shortcutSequenceString)'")

    // Special case: handle explicit modifier release
    if shortcutSequenceString.lowercased() == "release_modifiers"
      || shortcutSequenceString.lowercased() == "vk_none"
    {
      debugLog("[Controller] Executing explicit modifier release")
      // Release all possible modifiers
      let allModifiers: CGEventFlags = [
        .maskCommand, .maskShift, .maskAlternate, .maskControl, .maskSecondaryFn,
      ]
      releaseModifierKeys(allModifiers)
      return true
    }

    // Split the sequence string by spaces
    let individualShortcutStrings = shortcutSequenceString.split(separator: " ").map(String.init)

    // Process each shortcut in the sequence
    let delayBetweenShortcutsMicroseconds: useconds_t = 50000  // 50ms delay
    for (index, shortcutString) in individualShortcutStrings.enumerated() {
      // Check if this is a special modifier release command
      if shortcutString.lowercased() == "vk_none"
        || shortcutString.lowercased() == "release_modifiers"
      {
        debugLog("[Controller] Executing modifier release in sequence at position \(index + 1)")
        // Release all possible modifiers
        let allModifiers: CGEventFlags = [
          .maskCommand, .maskShift, .maskAlternate, .maskControl, .maskSecondaryFn,
        ]
        releaseModifierKeys(allModifiers)
        // Also release our tracked held modifiers
        releaseAllHeldModifiers()

        // Add delay if not the last item
        if index < individualShortcutStrings.count - 1 {
          usleep(delayBetweenShortcutsMicroseconds)
        }
        continue  // Move to next item in sequence
      }

      // Check for keydown: prefix (hold key down)
      if shortcutString.lowercased().hasPrefix("keydown:") {
        let keyName = String(shortcutString.dropFirst(8))  // Remove "keydown:" prefix
        debugLog("[Controller] Processing keydown: '\(keyName)' at position \(index + 1)")

        // Look up the key code
        if let keyCode = CompactShortcut.keyCode(for: keyName) {
          sendKeyDown(keyCode: keyCode)
        } else {
          debugLog("[Controller] Unknown key for keydown: '\(keyName)'")
          showAlert(
            title: "Invalid Keydown Command",
            message:
              "Unknown key: '\(keyName)' in keydown command.\n\nUse keys like: left_command, left_shift, left_option, left_control, etc."
          )
          releaseAllHeldModifiers()  // Safety cleanup
          appDelegate?.resetSequenceState()
          return false
        }

        // Add delay if not the last item
        if index < individualShortcutStrings.count - 1 {
          usleep(delayBetweenShortcutsMicroseconds)
        }
        continue  // Move to next item in sequence
      }

      // Check for keyup: prefix (release held key)
      if shortcutString.lowercased().hasPrefix("keyup:") {
        let keyName = String(shortcutString.dropFirst(6))  // Remove "keyup:" prefix
        debugLog("[Controller] Processing keyup: '\(keyName)' at position \(index + 1)")

        // Look up the key code
        if let keyCode = CompactShortcut.keyCode(for: keyName) {
          sendKeyUp(keyCode: keyCode)
        } else {
          debugLog("[Controller] Unknown key for keyup: '\(keyName)'")
          showAlert(
            title: "Invalid Keyup Command",
            message:
              "Unknown key: '\(keyName)' in keyup command.\n\nUse keys like: left_command, left_shift, left_option, left_control, etc."
          )
          releaseAllHeldModifiers()  // Safety cleanup
          appDelegate?.resetSequenceState()
          return false
        }

        // Add delay if not the last item
        if index < individualShortcutStrings.count - 1 {
          usleep(delayBetweenShortcutsMicroseconds)
        }
        continue  // Move to next item in sequence
      }

      // Check for delay: prefix (custom delay in milliseconds)
      if shortcutString.lowercased().hasPrefix("delay:") {
        let delayString = String(shortcutString.dropFirst(6))  // Remove "delay:" prefix
        debugLog("[Controller] Processing delay: '\(delayString)' ms at position \(index + 1)")

        // Parse the delay value
        guard let delayMs = Int(delayString) else {
          debugLog("[Controller] Invalid delay value: '\(delayString)'")
          showAlert(
            title: "Invalid Delay Command",
            message:
              "Invalid delay value: '\(delayString)'.\n\nUse a number in milliseconds (e.g., delay:500 for 500ms)."
          )
          releaseAllHeldModifiers()  // Safety cleanup
          appDelegate?.resetSequenceState()
          return false
        }

        // Validate delay range (0 to 10000ms = 10 seconds max)
        let clampedDelay = max(0, min(10000, delayMs))
        if clampedDelay != delayMs {
          debugLog("[Controller] Delay value clamped from \(delayMs)ms to \(clampedDelay)ms")
        }

        // Apply the delay (convert milliseconds to microseconds)
        if clampedDelay > 0 {
          let delayMicroseconds = useconds_t(clampedDelay * 1000)
          usleep(delayMicroseconds)
          debugLog("[Controller] Applied delay of \(clampedDelay)ms")
        } else {
          debugLog("[Controller] Skipping delay (0ms specified)")
        }

        // No additional delay after a delay command
        continue  // Move to next item in sequence
      }

      // Parse as normal shortcut
      guard let eventData = parseCompactShortcutToCGEventData(shortcutString) else {
        debugLog(
          "[Controller] Failed to parse part '\(shortcutString)' of sequence '\(shortcutSequenceString)'"
        )
        showAlert(
          title: "Invalid Shortcut Sequence",
          message:
            "Could not parse part '\(shortcutString)' in sequence: '\(shortcutSequenceString)'\n\nUse format like 'CSb Oa' (Cmd+Shift+b then Opt+a).\n\nSpecial commands:\n• vk_none or release_modifiers - Release all modifier keys\n\nCheck logs for details."
        )
        debugLog("[Controller] Shortcut parse failed. Resetting sequence state.")
        appDelegate?.resetSequenceState()  // Call reset on AppDelegate
        return false  // Indicate failure
      }

      // Execute the shortcut with currently held modifiers combined
      let currentHeldFlags = getCurrentModifierFlags()
      let combinedFlags = eventData.flags.union(currentHeldFlags)
      debugLog(
        "[Controller] Executing step \(index + 1)/\(individualShortcutStrings.count): KeyCode: \(eventData.keyCode), Flags: \(combinedFlags) (includes held modifiers)"
      )
      executeShortcut(keyCode: eventData.keyCode, flags: combinedFlags)

      // Add delay if not the last item
      if index < individualShortcutStrings.count - 1 {
        usleep(delayBetweenShortcutsMicroseconds)
      }
    }

    debugLog("[Controller] Successfully executed shortcut sequence: '\(shortcutSequenceString)'")
    return true  // Indicate success
  }

  func parseCompactShortcutToCGEventData(_ shortcut: String) -> (
    keyCode: CGKeyCode, flags: CGEventFlags
  )? {
    CompactShortcut.parse(shortcut)
  }

  private func executeShortcut(keyCode: CGKeyCode, flags: CGEventFlags) {
    // Get the system event source
    guard let source = CGEventSource(stateID: .hidSystemState) else {
      debugLog("Error: Failed to create CGEventSource.")
      return
    }
    // Add the tag to the source
    source.userData = leaderKeySyntheticEventTag

    // Define the event tap location
    let tapLocation = CGEventTapLocation.cghidEventTap

    // 1. Create and post the Key Down event
    guard let eventDown = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true)
    else {
      debugLog("Error: Failed to create KeyDown CGEvent.")
      return
    }
    eventDown.flags = flags  // Apply modifier flags
    // Set the user data field to identify this as a synthetic event
    eventDown.setIntegerValueField(.eventSourceUserData, value: leaderKeySyntheticEventTag)
    eventDown.post(tap: tapLocation)
    debugLog("Posted KeyDown: \(keyCode) with flags: \(flags)")

    // Add a small delay between down and up (optional)
    // usleep(10000) // e.g., 10 milliseconds

    // 2. Create and post the Key Up event
    guard let eventUp = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
    else {
      debugLog("Error: Failed to create KeyUp CGEvent.")
      return
    }
    eventUp.flags = flags  // Apply the *same* modifier flags
    // Set the user data field to identify this as a synthetic event
    eventUp.setIntegerValueField(.eventSourceUserData, value: leaderKeySyntheticEventTag)
    eventUp.post(tap: tapLocation)
    debugLog("Posted KeyUp: \(keyCode) with flags: \(flags)")
  }

  // Explicitly releases modifier keys to prevent them from appearing "stuck"
  // This is called when shortcut value is "release_modifiers" or "vk_none"
  // Usage in config: {"key": "r", "type": "shortcut", "value": "release_modifiers"}
  private func releaseModifierKeys(_ flags: CGEventFlags) {
    guard let source = CGEventSource(stateID: .hidSystemState) else {
      debugLog("Error: Failed to create CGEventSource for releasing modifiers.")
      return
    }
    source.userData = leaderKeySyntheticEventTag
    let tapLocation = CGEventTapLocation.cghidEventTap

    // Release Command keys
    if flags.contains(.maskCommand) {
      // Left Command (kVK_Command = 0x37)
      if let cmdUp = CGEvent(
        keyboardEventSource: source, virtualKey: CGKeyCode(kVK_Command), keyDown: false)
      {
        cmdUp.flags = []  // No flags - key is being released
        cmdUp.setIntegerValueField(.eventSourceUserData, value: leaderKeySyntheticEventTag)
        cmdUp.post(tap: tapLocation)
        debugLog("Released left Command key")
      }
      // Right Command (kVK_RightCommand = 0x36)
      if let cmdUp = CGEvent(
        keyboardEventSource: source, virtualKey: CGKeyCode(kVK_RightCommand), keyDown: false)
      {
        cmdUp.flags = []
        cmdUp.setIntegerValueField(.eventSourceUserData, value: leaderKeySyntheticEventTag)
        cmdUp.post(tap: tapLocation)
        debugLog("Released right Command key")
      }
    }

    // Release Shift keys
    if flags.contains(.maskShift) {
      // Left Shift (kVK_Shift = 0x38)
      if let shiftUp = CGEvent(
        keyboardEventSource: source, virtualKey: CGKeyCode(kVK_Shift), keyDown: false)
      {
        shiftUp.flags = []
        shiftUp.setIntegerValueField(.eventSourceUserData, value: leaderKeySyntheticEventTag)
        shiftUp.post(tap: tapLocation)
        debugLog("Released left Shift key")
      }
      // Right Shift (kVK_RightShift = 0x3C)
      if let shiftUp = CGEvent(
        keyboardEventSource: source, virtualKey: CGKeyCode(kVK_RightShift), keyDown: false)
      {
        shiftUp.flags = []
        shiftUp.setIntegerValueField(.eventSourceUserData, value: leaderKeySyntheticEventTag)
        shiftUp.post(tap: tapLocation)
        debugLog("Released right Shift key")
      }
    }

    // Release Option/Alt keys
    if flags.contains(.maskAlternate) {
      // Left Option (kVK_Option = 0x3A)
      if let optUp = CGEvent(
        keyboardEventSource: source, virtualKey: CGKeyCode(kVK_Option), keyDown: false)
      {
        optUp.flags = []
        optUp.setIntegerValueField(.eventSourceUserData, value: leaderKeySyntheticEventTag)
        optUp.post(tap: tapLocation)
        debugLog("Released left Option key")
      }
      // Right Option (kVK_RightOption = 0x3D)
      if let optUp = CGEvent(
        keyboardEventSource: source, virtualKey: CGKeyCode(kVK_RightOption), keyDown: false)
      {
        optUp.flags = []
        optUp.setIntegerValueField(.eventSourceUserData, value: leaderKeySyntheticEventTag)
        optUp.post(tap: tapLocation)
        debugLog("Released right Option key")
      }
    }

    // Release Control keys
    if flags.contains(.maskControl) {
      // Left Control (kVK_Control = 0x3B)
      if let ctrlUp = CGEvent(
        keyboardEventSource: source, virtualKey: CGKeyCode(kVK_Control), keyDown: false)
      {
        ctrlUp.flags = []
        ctrlUp.setIntegerValueField(.eventSourceUserData, value: leaderKeySyntheticEventTag)
        ctrlUp.post(tap: tapLocation)
        debugLog("Released Control key")
      }
      // Note: Right Control (0x3E) may not exist on all Mac keyboards
    }

    // Release Function key if present
    if flags.contains(.maskSecondaryFn) {
      // Function key (kVK_Function = 0x3F)
      if let fnUp = CGEvent(
        keyboardEventSource: source, virtualKey: CGKeyCode(kVK_Function), keyDown: false)
      {
        fnUp.flags = []
        fnUp.setIntegerValueField(.eventSourceUserData, value: leaderKeySyntheticEventTag)
        fnUp.post(tap: tapLocation)
        debugLog("Released Function key")
      }
    }
  }

  // Send only a keyDown event (for holding modifiers)
  private func sendKeyDown(keyCode: CGKeyCode, flags: CGEventFlags = []) {
    guard let source = CGEventSource(stateID: .hidSystemState) else {
      debugLog("Error: Failed to create CGEventSource for keyDown.")
      return
    }
    source.userData = leaderKeySyntheticEventTag
    let tapLocation = CGEventTapLocation.cghidEventTap

    guard let eventDown = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true)
    else {
      debugLog("Error: Failed to create KeyDown CGEvent.")
      return
    }
    eventDown.flags = flags
    eventDown.setIntegerValueField(.eventSourceUserData, value: leaderKeySyntheticEventTag)
    eventDown.post(tap: tapLocation)
    debugLog("Posted KeyDown only: \(keyCode) with flags: \(flags)")

    // Track this modifier as held if it's a modifier key
    if isModifierKey(keyCode: keyCode) {
      heldModifierKeys.insert(keyCode)
      debugLog("Tracking held modifier: \(keyCode)")
    }
  }

  // Send only a keyUp event (for releasing held modifiers)
  private func sendKeyUp(keyCode: CGKeyCode, flags: CGEventFlags = []) {
    guard let source = CGEventSource(stateID: .hidSystemState) else {
      debugLog("Error: Failed to create CGEventSource for keyUp.")
      return
    }
    source.userData = leaderKeySyntheticEventTag
    let tapLocation = CGEventTapLocation.cghidEventTap

    guard let eventUp = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
    else {
      debugLog("Error: Failed to create KeyUp CGEvent.")
      return
    }
    eventUp.flags = flags
    eventUp.setIntegerValueField(.eventSourceUserData, value: leaderKeySyntheticEventTag)
    eventUp.post(tap: tapLocation)
    debugLog("Posted KeyUp only: \(keyCode) with flags: \(flags)")

    // Remove from tracked held modifiers if it's a modifier key
    if isModifierKey(keyCode: keyCode) {
      heldModifierKeys.remove(keyCode)
      debugLog("Released held modifier: \(keyCode)")
    }
  }

  // Check if a keyCode is a modifier key
  private func isModifierKey(keyCode: CGKeyCode) -> Bool {
    let modifierKeyCodes: Set<CGKeyCode> = [
      CGKeyCode(kVK_Command),
      CGKeyCode(kVK_RightCommand),
      CGKeyCode(kVK_Shift),
      CGKeyCode(kVK_RightShift),
      CGKeyCode(kVK_Option),
      CGKeyCode(kVK_RightOption),
      CGKeyCode(kVK_Control),
      CGKeyCode(kVK_RightControl),
      CGKeyCode(kVK_Function),
      CGKeyCode(kVK_CapsLock),
    ]
    return modifierKeyCodes.contains(keyCode)
  }

  // Release all currently held modifier keys
  private func releaseAllHeldModifiers() {
    guard !heldModifierKeys.isEmpty else { return }

    debugLog("Releasing all held modifiers: \(heldModifierKeys)")
    for keyCode in heldModifierKeys {
      sendKeyUp(keyCode: keyCode)
    }
    heldModifierKeys.removeAll()
  }

  // Get current modifier flags based on held modifiers
  private func getCurrentModifierFlags() -> CGEventFlags {
    var flags: CGEventFlags = []

    for keyCode in heldModifierKeys {
      switch Int(keyCode) {
      case kVK_Command, kVK_RightCommand:
        flags.insert(.maskCommand)
      case kVK_Shift, kVK_RightShift:
        flags.insert(.maskShift)
      case kVK_Option, kVK_RightOption:
        flags.insert(.maskAlternate)
      case kVK_Control, kVK_RightControl:
        flags.insert(.maskControl)
      case kVK_Function:
        flags.insert(.maskSecondaryFn)
      case kVK_CapsLock:
        flags.insert(.maskAlphaShift)
      default:
        break
      }
    }

    return flags
  }
  // --- Shortcut Execution Helpers --- END ---

  /// Find the screen containing the mouse cursor, fallback to main screen
  private func screenContainingMouse(_ mouseLocation: NSPoint) -> NSScreen? {
    NSScreen.screens.first { $0.frame.contains(mouseLocation) } ?? NSScreen.main
  }
}

class DontActivateConfiguration {
  let configuration = NSWorkspace.OpenConfiguration()

  static var shared = DontActivateConfiguration()

  init() {
    configuration.activates = false
  }
}
